- .gitignore
- src/main/java/org/jahia/modules/healthcheck/servlet/HealthcheckJSONProducer.java
- src/main/resources/META-INF/spring/healthcheck.xml
https://jira.jahia.org/browse/PAAS-415
> PAAS-415: token read from configuration file and environment variable

- src/main/java/org/jahia/modules/healthcheck/servlet/HealthcheckJSONProducer.java
- src/main/resources/META-INF/spring/healthcheck.xml
JIRA issue: https://jira.jahia.org/browse/PAAS-415
> PAAS-415: fix of the healthcheck token read from a bad source.

- src/main/java/org/jahia/modules/healthcheck/servlet/HealthcheckJSONProducer.java
JIRA issue: https://jira.jahia.org/browse/PAAS-656
> PAAS-656: added JSON as the response content type.

- src/main/resources/jnt_healthcheckTokenPanel/html/healthcheckTokenPanel.jsp
JIRA issue: https://jira.jahia.org/browse/BACKLOG-14148
Use post instead of get (as get are forbidden by default)
> BACKLOG-14148: Use post instead of get for actions

- LICENSE
JIRA issue: https://jira.jahia.org/browse/OPENCODE-103
Following discussion with Stephanie
> OPENCODE-103 - Added license

- README.md
- src/main/java/org/jahia/modules/healthcheck/probes/RequestLoadProbe.java
JIRA issue: https://jira.jahia.org/browse/PAAS-:
Short description: make the load thresholds configurable
> PAAS-1312: make the load thresholds configurable

- README.md
- src/main/java/org/jahia/modules/healthcheck/servlet/HealthcheckJSONProducer.java
JIRA issue: https://jira.jahia.org/browse/PAAS-1318
Short description: allow to contribute healthcheck tokens via karaf
> PAAS-1318: allow to contribute healthcheck tokens via karaf

- src/main/java/org/jahia/modules/healthcheck/servlet/HealthcheckJSONProducer.java
JIRA issue: https://jira.jahia.org/browse/PAAS-1310
> PAAS-1310: remove a useless logger

- README.md
- pom.xml
- src/main/java/org/jahia/modules/healthcheck/config/HealthcheckConfigProvider.java
- src/main/java/org/jahia/modules/healthcheck/servlet/HealthcheckJSONProducer.java
- src/main/resources/META-INF/spring/healthcheck.xml
JIRA issue: https://jira.jahia.org/browse/PAAS-1318
Short description: configure token via karaf
> Paas 1318 configure token via karaf

- README.md
- src/main/java/org/jahia/modules/healthcheck/servlet/HealthcheckJSONProducer.java
JIRA issue: https://jira.jahia.org/browse/PAAS-1311
Short description:make the HTTP status of RED healthchecks configurable
> PAAS-1311: make the HTTP status of RED healthchecks configurable

- README.md
- src/main/java/org/jahia/modules/healthcheck/probes/RequestLoadProbe.java
JIRA issue: https://jira.jahia.org/browse/PAAS-1312
Short description: make the request and session load thresholds configurable
> PAAS-1312: make the request and session load thresholds configurable

- src/main/java/org/jahia/modules/healthcheck/servlet/HealthcheckJSONProducer.java
JIRA issue: https://jira.jahia.org/browse/PAAS-1318
Short description: fixed error in the token comparison
> PAAS-1318: fixed error in the token comparison

- src/main/java/org/jahia/modules/healthcheck/servlet/HealthcheckJSONProducer.java
JIRA issue: https://jira.jahia.org/browse/PAAS-1318
Short description:fixed a typo on the karaf token configuration comparison
> PAAS-1318: fixed a typo on the karaf token configuration comparison

- src/main/java/org/jahia/modules/healthcheck/probes/RequestLoadProbe.java
JIRA issue: https://jira.jahia.org/browse/PAAS-1312
Short description: added debug logs to display thresholds
> PAAS-1312: added debug logs to display thresholds

- README.md
- src/main/java/org/jahia/modules/healthcheck/HealthcheckConstants.java
- src/main/java/org/jahia/modules/healthcheck/config/HealthcheckConfigProvider.java
- src/main/java/org/jahia/modules/healthcheck/servlet/HealthcheckJSONProducer.java
JIRA issue: https://jira.jahia.org/browse/PAAS-1351
> PAAS-1351: added severity thresholds to the healthcheck

- README.md
- src/main/java/org/jahia/modules/healthcheck/HealthcheckConstants.java
- src/main/java/org/jahia/modules/healthcheck/config/HealthcheckConfigProvider.java
- src/main/java/org/jahia/modules/healthcheck/servlet/HealthcheckJSONProducer.java
JIRA issue: https://jira.jahia.org/browse/PAAS-1388
> PAAS-1388: add severity thresholds to the /healthcheck servlet

- src/main/java/org/jahia/modules/healthcheck/servlet/HealthcheckJSONProducer.java
JIRA issue: https://jira.jahia.org/browse/PAAS-1410
> PAAS-1410: force the healthcheck to output its payload when the status is RED

- src/main/java/org/jahia/modules/healthcheck/servlet/HealthcheckJSONProducer.java
JIRA issue: https://jira.jahia.org/browse/PAAS-1410
> PAAS-1410: output the payload of the healthcheck when the status is RED

- src/main/java/org/jahia/modules/healthcheck/servlet/HealthcheckJSONProducer.java
JIRA issue: https://jira.jahia.org/browse/PAAS-1410
> PAAS-1410: rearrange the code so that it works.

- src/main/java/org/jahia/modules/healthcheck/servlet/HealthcheckJSONProducer.java
JIRA issue: https://jira.jahia.org/browse/PAAS-1410
> PAAS-1410: rearrange the code so that it works

- src/main/java/org/jahia/modules/healthcheck/HealthcheckConstants.java
- src/main/java/org/jahia/modules/healthcheck/servlet/HealthcheckJSONProducer.java
JIRA issue: https://jira.jahia.org/browse/PAAS-1438
> PAAS-1438: add the probe severity in the healthcheck payload

- src/main/java/org/jahia/modules/healthcheck/HealthcheckConstants.java
- src/main/java/org/jahia/modules/healthcheck/servlet/HealthcheckJSONProducer.java
JIRA issue: https://jira.jahia.org/browse/PAAS-1438
> PAAS-1438: add severity level in each probe's payload

- src/main/java/org/jahia/modules/healthcheck/config/HealthcheckConfigProvider.java
JIRA issue: https://jira.jahia.org/browse/PAAS-1439
> PAAS-1439: fix the configuration key parsing

- src/main/java/org/jahia/modules/healthcheck/servlet/HealthcheckJSONProducer.java
JIRA issue: https://jira.jahia.org/browse/PAAS-1444
> PAAS-1444: switch the default load probe's severity to HIGH

- src/main/java/org/jahia/modules/healthcheck/servlet/HealthcheckJSONProducer.java
JIRA issue: https://jira.jahia.org/browse/PAAS-1438
> PAAS-1438: fix previously introduced bug

- src/main/java/org/jahia/modules/healthcheck/servlet/HealthcheckJSONProducer.java
JIRA issue: https://jira.jahia.org/browse/PAAS-1438
> Paas 1438 reintroduce skip of below severity threshold probes
